### ISSUE TITLE
No categ on about page

### ISSUE THREAD

**Issue by johannpinson** [hetic-newsroom/heticiens.news#50]
Hi guys,

I think may be an error with the filter function because on the `/about` page, I don't see the categories inside the menu.

https://github.com/hetic-newsroom/heticiens.news/blob/b4569890df80c60d5a0681b01c393db05fd67341/pages/_app.tsx#L59-L62

At first, I thought about L47-49, but SSR is working well on this page.

It's maybe a bug elsewhere, but I didn't try to make tests in local, I didn't find the install readme 😛 

Have fun!

Screenshot
<img width="986" alt="Capture d’écran 2021-03-01 à 15 20 19" src="https://user-images.githubusercontent.com/2202989/109509951-be8a7380-7aa1-11eb-8c49-894dd1f14c23.png">

**Comment by johannpinson** [comment]
ping @GitSquared @Satwa 😉

**Comment by GitSquared** [comment]
Thanks @johannpinson , can repro, will investigate today!

**Comment by GitSquared** [comment]
Fixed, Vercel should update it in production rn :+1:

Thanks for the detailed report.

Re: readme, we're not going to put one up for now because running the app in local requires pulling some env variables from our Vercel account.

**Comment by johannpinson** [comment]
Ok perfect!

And no worries about the readme, that was more a joke than a real asking 😄
